[build]
builder = "nixpacks"
buildCommand = "cd BE && pip install -r requirements.txt"

[deploy]
startCommand = "cd BE && uvicorn main:app --host 0.0.0.0 --port $PORT"
restartPolicyType = "on_failure"